openapi: 3.0.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: 'https://konghq.com'
  description: |-
    OpenAPI 3.0 spec for Kong Gateway's Admin API.

    You can lean more about Kong Gateway at [docs.konghq.com](https://docs.konghq.com)
    .Give Kong a star at [Kong/kong](https://github.com/kong/kong) repository.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  title: Konnect Control Planes Configuration
  version: 0.0.1
servers:
  - url: 'https://us.api.konghq.com/v2'
    description: United-States Production region
  - url: 'https://eu.api.konghq.com/v2'
    description: Europe Production region
  - url: 'https://au.api.konghq.com/v2'
    description: Australia Production region
  - url: 'https://me.api.konghq.com/v2'
    description: Middle-East Production region
paths:
  '/control-planes/{controlPlaneId}/expected-config-version':
    get:
      operationId: get-expected-config-version
      summary: Fetch Expected Config Version
      description: Retrieve the expected config version for this control plane. The expected config version can be used to verify if the config version of a data plane node is up to date with the control plane. The config version will be the same if they are in sync.
      responses:
        '200':
          $ref: '#/components/responses/GetExpectedConfigVersionResponse'
      tags:
        - DP Nodes
    parameters:
      - $ref: '#/components/parameters/controlPlaneId'
  '/control-planes/{controlPlaneId}/config-stores':
    get:
      operationId: list-config-stores
      summary: List all config stores for a control plane
      parameters:
        - $ref: '#/components/parameters/controlPlaneId'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/PageAfter'
      responses:
        '200':
          $ref: '#/components/responses/ListConfigStoresResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/ConfigStoreUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Config Stores
    post:
      operationId: create-config-store
      summary: Create Config Store
      description: Create a Config Store
      parameters:
        - $ref: '#/components/parameters/controlPlaneId'
      requestBody:
        $ref: '#/components/requestBodies/CreateConfigStoreRequest'
      responses:
        '201':
          $ref: '#/components/responses/ConfigStoreResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                ConfigStoreNameBadRequestExample:
                  $ref: '#/components/examples/ConfigStoreNameBadRequestExample'
        '401':
          $ref: '#/components/responses/ConfigStoreUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
      tags:
        - Config Stores
  '/control-planes/{controlPlaneId}/config-stores/{configStoreId}':
    parameters:
      - $ref: '#/components/parameters/controlPlaneId'
      - $ref: '#/components/parameters/configStoreId'
    get:
      operationId: get-config-store
      summary: Fetch Config Store
      description: Returns a Config Store
      responses:
        '200':
          $ref: '#/components/responses/ConfigStoreResponse'
        '401':
          $ref: '#/components/responses/ConfigStoreUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Config Stores
    put:
      operationId: update-config-store
      summary: Update an individual Config Store
      description: Updates a Config Store
      requestBody:
        $ref: '#/components/requestBodies/UpdateConfigStoreRequest'
      responses:
        '200':
          $ref: '#/components/responses/ConfigStoreResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                ConfigStoreNameBadRequestExample:
                  $ref: '#/components/examples/ConfigStoreNameBadRequestExample'
        '401':
          $ref: '#/components/responses/ConfigStoreUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ConfigStoreNotFound'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
      tags:
        - Config Stores
    delete:
      operationId: delete-config-store
      summary: Delete Config Store
      description: Removes a config store
      parameters:
        - name: force
          in: query
          description: 'If true, delete specified config store and all secrets, even if there are secrets linked to the config store If false, do not allow deletion if there are secrets linked to the config store'
          schema:
            type: string
            default: 'false'
            enum:
              - 'true'
              - 'false'
      responses:
        '204':
          description: Config Store was deleted successfully.
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                DeleteConfigStoreBadRequestExample:
                  $ref: '#/components/examples/DeleteConfigStoreBadRequestExample'
        '401':
          $ref: '#/components/responses/ConfigStoreUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Config Stores
  '/control-planes/{controlPlaneId}/config-stores/{configStoreId}/secrets':
    parameters:
      - $ref: '#/components/parameters/controlPlaneId'
      - $ref: '#/components/parameters/configStoreId'
    post:
      operationId: create-config-store-secret
      summary: Create Config Store Secret
      description: Creates a secret for a Config Store.
      requestBody:
        $ref: '#/components/requestBodies/CreateConfigStoreSecretRequest'
      responses:
        '201':
          $ref: '#/components/responses/ConfigStoreSecretResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                ConfigStoreSecretBadRequestExample:
                  $ref: '#/components/examples/ConfigStoreSecretBadRequestExample'
        '401':
          $ref: '#/components/responses/ConfigStoreSecretUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ConfigStoreSecretNotFound'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
      tags:
        - Config Store Secrets
    get:
      operationId: list-config-store-secrets
      summary: List Config Store Secrets
      description: Returns a collection of all secrets for a Config Store.
      parameters:
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/PageAfter'
      responses:
        '200':
          $ref: '#/components/responses/ListConfigStoreSecretsResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/ConfigStoreSecretUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ConfigStoreSecretNotFound'
      tags:
        - Config Store Secrets
  '/control-planes/{controlPlaneId}/config-stores/{configStoreId}/secrets/{key}':
    parameters:
      - $ref: '#/components/parameters/controlPlaneId'
      - $ref: '#/components/parameters/configStoreId'
      - name: key
        in: path
        description: Config Store Secret key
        required: true
        schema:
          type: string
          example: ConfigStoreSecretKey
    get:
      operationId: get-config-store-secret
      summary: Fetch Config Store Secret
      description: Returns a secret for the Config Store.
      responses:
        '200':
          $ref: '#/components/responses/ConfigStoreSecretResponse'
        '401':
          $ref: '#/components/responses/ConfigStoreSecretUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ConfigStoreSecretNotFound'
      tags:
        - Config Store Secrets
    put:
      operationId: update-config-store-secret
      summary: Update Config Store Secret
      description: Updates a secret for a Config Store.
      requestBody:
        $ref: '#/components/requestBodies/UpdateConfigStoreSecretRequest'
      responses:
        '200':
          $ref: '#/components/responses/ConfigStoreSecretResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                ConfigStoreSecretBadRequestExample:
                  $ref: '#/components/examples/ConfigStoreSecretBadRequestExample'
        '401':
          $ref: '#/components/responses/ConfigStoreSecretUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ConfigStoreSecretNotFound'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
      tags:
        - Config Store Secrets
    delete:
      operationId: delete-config-store-secret
      summary: Delete Config Store Secret
      description: Removes a secret from a Config Store.
      responses:
        '204':
          description: Secret for the Config Store was deleted successfully.
        '401':
          $ref: '#/components/responses/ConfigStoreSecretUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/ConfigStoreSecretNotFound'
      tags:
        - Config Store Secrets
  '/control-planes/{controlPlaneId}/observability/debug-sessions':
    get:
      operationId: list-debug-sessions
      summary: List all debug sessions for a control plane
      parameters:
        - $ref: '#/components/parameters/controlPlaneId'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/PageAfter'
      responses:
        '200':
          $ref: '#/components/responses/ListDebugSessionsResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/DebugSessionUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Debug Sessions
    post:
      operationId: create-debug-session
      summary: Create Debug Session
      description: Create Debug Session
      parameters:
        - $ref: '#/components/parameters/controlPlaneId'
      requestBody:
        $ref: '#/components/requestBodies/CreateDebugSessionRequest'
      responses:
        '201':
          $ref: '#/components/responses/DebugSessionResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/DebugSessionUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
      tags:
        - Debug Sessions
  '/control-planes/{controlPlaneId}/observability/debug-sessions/{debugSessionId}':
    parameters:
      - $ref: '#/components/parameters/controlPlaneId'
      - $ref: '#/components/parameters/debugSessionId'
    get:
      operationId: get-debug-session
      summary: Fetch a Debug Session
      description: Returns a Debug Session
      responses:
        '200':
          $ref: '#/components/responses/DebugSessionResponse'
        '401':
          $ref: '#/components/responses/DebugSessionUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Debug Sessions
    delete:
      operationId: delete-debug-session
      summary: Delete a Debug Session
      description: Deletes a Debug Session
      responses:
        '204':
          description: The debug session was deleted successfully.
        '401':
          $ref: '#/components/responses/DebugSessionUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Debug Sessions
  '/control-planes/{controlPlaneId}/observability/debug-sessions/{debugSessionId}/stop':
    parameters:
      - $ref: '#/components/parameters/controlPlaneId'
      - $ref: '#/components/parameters/debugSessionId'
    post:
      operationId: stop-debug-session
      summary: Stops an active Debug Session
      description: Stops an active Debug Session
      responses:
        '200':
          $ref: '#/components/responses/DebugSessionStopResponse'
        '401':
          $ref: '#/components/responses/DebugSessionUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Debug Sessions
  '/control-planes/{controlPlaneId}/observability/debug-sessions/data':
    get:
      operationId: get-debug-sessions-data
      summary: Gets data for a debug session (internal only)
      parameters:
        - $ref: '#/components/parameters/controlPlaneId'
      responses:
        '200':
          description: Data response
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/DebugSessionUnauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Debug Sessions
  '/control-planes/{controlPlaneId}/core-entities/custom-plugins':
    get:
      operationId: list-custom-plugin
      summary: List all CustomPlugins
      description: List all CustomPlugins
      parameters:
        - $ref: '#/components/parameters/PaginationSize'
        - $ref: '#/components/parameters/PaginationOffset'
        - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing CustomPlugins
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CustomPlugin'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
        - CustomPlugins
    parameters:
      - $ref: '#/components/parameters/controlPlaneId'
    post:
      operationId: create-custom-plugin
      summary: Create a new CustomPlugin
      description: Create a new CustomPlugin
      requestBody:
        description: Description of the new CustomPlugin for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomPlugin'
      responses:
        '201':
          description: Successfully created CustomPlugin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomPlugin'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
        - CustomPlugins
  '/control-planes/{controlPlaneId}/core-entities/custom-plugins/{CustomPluginId}':
    delete:
      operationId: delete-custom-plugin
      summary: Delete a CustomPlugin
      description: Delete a CustomPlugin
      parameters:
        - $ref: '#/components/parameters/CustomPluginId'
      responses:
        '204':
          description: Successfully deleted CustomPlugin or the resource didn't exist
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
        - CustomPlugins
    get:
      operationId: get-custom-plugin
      summary: Fetch a CustomPlugin
      description: Get a CustomPlugin using ID or name.
      responses:
        '200':
          description: Successfully fetched CustomPlugin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomPlugin'
        '401':
          $ref: '#/components/responses/HTTP401Error'
        '404':
          description: Resource does not exist
      tags:
        - CustomPlugins
    parameters:
      - $ref: '#/components/parameters/CustomPluginId'
      - $ref: '#/components/parameters/controlPlaneId'
    put:
      operationId: upsert-custom-plugin
      summary: Upsert a CustomPlugin
      description: Create or Update CustomPlugin using ID or name.
      requestBody:
        description: Description of the CustomPlugin
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomPlugin'
      responses:
        '200':
          description: Successfully upserted CustomPlugin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomPlugin'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
        - CustomPlugins
components:
  parameters:
    CustomPluginId:
      description: ID of the CustomPlugin to lookup
      example: ''
      in: path
      name: CustomPluginId
      required: true
      schema:
        type: string
    PageAfter:
      name: 'page[after]'
      description: 'Request the next page of data, starting with the item after this parameter.'
      required: false
      in: query
      allowEmptyValue: true
      schema:
        type: string
        example: ewogICJpZCI6ICJoZWxsbyB3b3JsZCIKfQ
    PageSize:
      name: 'page[size]'
      description: The maximum number of items to include per page. The last page of a collection may include fewer items.
      required: false
      in: query
      allowEmptyValue: true
      schema:
        type: integer
        example: 10
    PaginationOffset:
      description: Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
      in: query
      name: offset
      schema:
        type: string
    PaginationSize:
      description: Number of resources to be returned.
      in: query
      name: size
      schema:
        type: integer
        default: 100
        maximum: 1000
        minimum: 1
    PaginationTagsFilter:
      description: 'A list of tags to filter the list of resources on. Multiple tags can be concatenated using '','' to mean AND or using ''/'' to mean OR.'
      example: 'tag1,tag2'
      in: query
      name: tags
      schema:
        type: string
    configStoreId:
      schema:
        type: string
        format: uuid
        example: d32d905a-ed33-46a3-a093-d8f536af9a8a
      name: configStoreId
      in: path
      required: true
      description: Config Store identifier
    controlPlaneId:
      name: controlPlaneId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 9524ec7d-36d9-465d-a8c5-83a3c9390458
      description: The UUID of your control plane. This variable is available in the Konnect manager.
    debugSessionId:
      schema:
        type: string
        format: uuid
        example: d32d905a-ed33-46a3-a093-d8f536af9a8a
      name: debugSessionId
      in: path
      required: true
      description: Debug Session identifier
  schemas:
    ConfigStore:
      type: object
      properties:
        id:
          description: The Config Store ID.
          type: string
          format: uuid
          example: b9e81174-b5bb-4638-a3c3-8afe61a0abf8
          readOnly: true
        name:
          description: The name of the Config Store
          type: string
          example: My Name
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
    CreateConfigStore:
      description: The request schema to create a Config Store.
      type: object
      properties:
        name:
          type: string
          example: Config Store
          maxLength: 100
          minLength: 1
      additionalProperties: false
      title: Create Config Store Request
    UpdateConfigStore:
      description: The request schema to update a Config Store.
      type: object
      properties:
        name:
          type: string
          example: Config Store
          maxLength: 100
          minLength: 1
      additionalProperties: false
      title: Update Config Store Request
    ConfigStoreSecret:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
    CreateConfigStoreSecret:
      type: object
      properties:
        key:
          type: string
          maxLength: 512
          minLength: 1
        value:
          type: string
          maxLength: 5120
          minLength: 1
      required:
        - key
        - value
    UpdateConfigStoreSecret:
      type: object
      properties:
        value:
          type: string
          maxLength: 5120
          minLength: 1
      required:
        - value
    DebugSession:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          description: The optional session name.
          type: string
        max_samples:
          description: The maximum amount of samples to collect per data plane.
          type: integer
          example: 10
        sampling_rule:
          description: An expression used to filter the requests to sample.
          type: string
          example: http.path == "/my-path"
          nullable: true
        duration_secs:
          description: The duration of the debug session in seconds.
          type: integer
          example: 300
        started_at:
          description: An ISO-8601 timestamp representation of start date.
          type: string
          format: date-time
          example: '2024-11-04T20:10:06.927Z'
          readOnly: true
        stopped_at:
          description: An ISO-8601 timestamp representation of stop date.
          type: string
          format: date-time
          example: '2022-11-04T20:10:06.927Z'
          readOnly: true
        completed_at:
          description: An ISO-8601 timestamp representation of completion date.
          type: string
          format: date-time
          example: '2022-11-04T20:10:06.927Z'
          readOnly: true
        timed_out:
          description: Determines whether the target did not respond in time before the sampling time elapsed.
          type: boolean
          readOnly: true
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
        targets:
          description: The data plane nodes to collect samples from.
          type: array
          items:
            type: string
            format: uuid
            example: 5f9fd312-a987-4628-b4c5-bb4f4fddd5f7
            description: Unique identifier of the data plane node.
    CustomPlugin:
      type: object
      properties:
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          readOnly: true
        handler:
          type: string
        id:
          type: string
          nullable: true
        name:
          type: string
        schema:
          type: string
        tags:
          type: array
          items:
            type: string
        updated_at:
          description: Unix epoch when the resource was last updated.
          type: integer
          readOnly: true
      example:
        handler: 'return { VERSION = ''1.0,0'', PRIORITY = 500, access = function(self, config) kong.service.request.set_header(config.name, config.value) end }'
        id: 868346aa-1105-4b77-8346-aa1105fb77c4
        name: set-header
        schema: 'return { name = ''set-header'', fields = { { protocols = require(''kong.db.schema.typedefs'').protocols_http }, { config = { type = ''record'', fields = { { name = { description = ''The name of the header to set.'', type = ''string'', required = true } }, { value = { description = ''The value for the header.'', type = ''string'', required = true } } } } } } }'
      additionalProperties: false
      required:
        - name
        - schema
        - handler
    GatewayUnauthorizedError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
        - message
        - status
    PaginationNextResponse:
      description: URI to the next page (may be null)
      type: string
    PaginationOffsetResponse:
      description: Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
      type: string
    BaseError:
      description: standard error
      type: object
      properties:
        status:
          description: |
            The HTTP status code of the error. Useful when passing the response
            body to child properties in a frontend UI. Must be returned as an integer.
          type: integer
          readOnly: true
        title:
          description: |
            A short, human-readable summary of the problem. It should not
            change between occurences of a problem, except for localization.
            Should be provided as "Sentence case" for direct use in the UI.
          type: string
          readOnly: true
        type:
          description: The error type.
          type: string
          readOnly: true
        instance:
          description: |
            Used to return the correlation ID back to the user, in the format
            kong:trace:<correlation_id>. This helps us find the relevant logs
            when a customer reports an issue.
          type: string
          readOnly: true
        detail:
          description: |
            A human readable explanation specific to this occurence of the problem.
            This field may contain request/entity data to help the user understand
            what went wrong. Enclose variable values in square brackets. Should be
            provided as "Sentence case" for direct use in the UI.
          type: string
          readOnly: true
      required:
        - status
        - title
        - instance
        - detail
      title: Error
    InvalidRules:
      description: invalid parameters rules
      type: string
      enum:
        - required
        - is_array
        - is_base64
        - is_boolean
        - is_date_time
        - is_integer
        - is_null
        - is_number
        - is_object
        - is_string
        - is_uuid
        - is_fqdn
        - is_arn
        - unknown_property
        - is_label
        - matches_regex
        - invalid
        - is_supported_network_availability_zone_list
        - is_supported_network_cidr_block
        - is_supported_provider_region
      nullable: true
      readOnly: true
    InvalidParameterStandard:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          $ref: '#/components/schemas/InvalidRules'
        source:
          type: string
          example: body
        reason:
          type: string
          example: is a required field
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
    InvalidParameterMinimumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - min_length
            - min_digits
            - min_lowercase
            - min_uppercase
            - min_symbols
            - min_items
            - min
          nullable: false
          readOnly: true
        minimum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must have at least 8 characters
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - minimum
    InvalidParameterMaximumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - max_length
            - max_items
            - max
          nullable: false
          readOnly: true
        maximum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must not have more than 8 characters
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - maximum
    InvalidParameterChoiceItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - enum
          nullable: false
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        choices:
          type: array
          items: {}
          minItems: 1
          nullable: false
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - choices
    InvalidParameterDependentItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - dependent_fields
          nullable: true
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        dependents:
          type: array
          items: {}
          nullable: true
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
        - field
        - rule
        - reason
        - dependents
    InvalidParameters:
      description: invalid parameters
      type: array
      items:
        oneOf:
          - $ref: '#/components/schemas/InvalidParameterStandard'
          - $ref: '#/components/schemas/InvalidParameterMinimumLength'
          - $ref: '#/components/schemas/InvalidParameterMaximumLength'
          - $ref: '#/components/schemas/InvalidParameterChoiceItem'
          - $ref: '#/components/schemas/InvalidParameterDependentItem'
      minItems: 1
      nullable: false
      uniqueItems: true
    BadRequestError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          required:
            - invalid_parameters
          properties:
            invalid_parameters:
              $ref: '#/components/schemas/InvalidParameters'
    UnauthorizedError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 401
            title:
              example: Unauthorized
            type:
              example: 'https://httpstatuses.com/401'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Invalid credentials
    ForbiddenError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 403
            title:
              example: Forbidden
            type:
              example: 'https://httpstatuses.com/403'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Forbidden
    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 404
            title:
              example: Not Found
            type:
              example: 'https://httpstatuses.com/404'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Not found
    CursorMetaPage:
      type: object
      properties:
        first:
          description: URI to the first page
          type: string
          format: path
        last:
          description: URI to the last page
          type: string
          format: path
        next:
          description: URI to the next page
          type: string
          format: path
          nullable: true
        previous:
          description: URI to the previous page
          type: string
          format: path
          nullable: true
        size:
          description: Requested page size
          type: number
          example: 10
      required:
        - size
        - next
        - previous
    CursorMeta:
      description: Pagination metadata.
      type: object
      properties:
        page:
          $ref: '#/components/schemas/CursorMetaPage'
      required:
        - page
    CreatedAt:
      description: An ISO-8601 timestamp representation of entity creation date.
      type: string
      format: date-time
      example: '2022-11-04T20:10:06.927Z'
      readOnly: true
    UpdatedAt:
      description: An ISO-8601 timestamp representation of entity update date.
      type: string
      format: date-time
      example: '2022-11-04T20:10:06.927Z'
      readOnly: true
    UnsupportedMediaTypeError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 415
            title:
              example: UnsupportedMediaType
            type:
              example: 'https://httpstatuses.com/415'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: UnsupportedMediaType
    UUID:
      description: Contains a unique identifier used by the API for this resource.
      type: string
      format: uuid
      example: 5f9fd312-a987-4628-b4c5-bb4f4fddd5f7
      readOnly: true
  examples:
    ConfigStoreExample:
      value:
        id: e7a4f6c0-5777-4a37-bcb9-2d37d3b362ee
        name: Config Store
        created_at: '2024-01-01T00:00:00.000Z'
        updated_at: '2024-01-01T00:00:00.000Z'
    ConfigStoreSecretExample:
      value:
        key: ConfigStoreSecretKey
        value: ConfigStoreSecretValue
        created_at: '2024-01-01T00:00:00.000Z'
        updated_at: '2024-01-01T00:00:00.000Z'
    CreateConfigStoreRequestExample:
      summary: Create Config Store Request
      value:
        name: Config Store
    CreateConfigStoreSecretRequestExample:
      summary: Create Config Store Secret Request
      value:
        key: ConfigStoreSecretKey
        value: ConfigStoreSecretValue
    ConfigStoreNameBadRequestExample:
      value:
        status: 400
        title: Invalid Request
        instance: 'kong:trace:8405749052424858251'
        detail: Invalid Parameters
        invalid_parameters:
          - field: name
            rule: min_length
            minimum: 1
            reason: name must be longer than or equal to 1 characters
    ConfigStoreSecretBadRequestExample:
      value:
        status: 400
        title: Invalid Request
        instance: 'kong:trace:8405749052424858251'
        detail: Invalid Parameters
        invalid_parameters:
          - field: key
            rule: min_length
            minimum: 1
            reason: name must be longer than or equal to 1 characters
    UpdateConfigStoreRequestExample:
      summary: Update Config Store Request
      value:
        name: Config Store with Updated Name
    UpdateConfigStoreSecretRequestExample:
      summary: Update Config Store Secret Request
      value:
        value: ConfigStoreSecretValue
    DeleteConfigStoreBadRequestExample:
      value:
        status: 400
        title: Invalid Request
        instance: 'kong:trace:1433447772874964729'
        detail: Invalid Parameters
        invalid_parameters:
          - field: force
            rule: required
            reason: This Config Store has 4 secrets. These must be individually removed before deletion or the force=true query param can be used to automatically delete associated entities.”
            source: query
    CreateDebugSessionRequestExample:
      summary: Create Debug Session Request
      value:
        id: e7a4f6c0-5777-4a37-bcb9-2d37d3b362ee
        max_samples: 10
        targets:
          - ae853602-23c7-4218-9071-82fdef3a1efe
    DebugSessionExample:
      value:
        id: e7a4f6c0-5777-4a37-bcb9-2d37d3b362ee
        max_samples: 10
        duration_secs: 300
        created_at: '2024-10-01T20:10:00.000Z'
        updated_at: '2024-10-01T20:10:00.000Z'
    UnauthorizedExample:
      value:
        status: 401
        title: Unauthorized
        instance: 'kong:trace:8347343766220159418'
        detail: Unauthorized
    ForbiddenExample:
      value:
        status: 403
        title: Forbidden
        instance: 'kong:trace:2723154947768991354'
        detail: You do not have permission to perform this action
    NotFoundExample:
      value:
        status: 404
        title: Not Found
        instance: 'kong:trace:6816496025408232265'
        detail: Not Found
    UnsupportedMediaTypeExample:
      value:
        status: 415
        title: Unsupported Media Type
        instance: 'kong:trace:8347343766220159418'
        detail: 'This API only supports requests with `Content-Type: application/json`'
  requestBodies:
    CreateConfigStoreRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateConfigStore'
          examples:
            CreateConfigStoreRequestExample:
              $ref: '#/components/examples/CreateConfigStoreRequestExample'
    CreateConfigStoreSecretRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateConfigStoreSecret'
          examples:
            CreateConfigStoreRequestExample:
              $ref: '#/components/examples/CreateConfigStoreSecretRequestExample'
    UpdateConfigStoreRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateConfigStore'
          examples:
            UpdateConfigStoreRequestExample:
              $ref: '#/components/examples/UpdateConfigStoreRequestExample'
    UpdateConfigStoreSecretRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateConfigStoreSecret'
          examples:
            UpdateConfigStoreSecretRequestExample:
              $ref: '#/components/examples/UpdateConfigStoreSecretRequestExample'
    CreateDebugSessionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DebugSession'
          examples:
            CreateDebugSessionRequestExample:
              $ref: '#/components/examples/CreateDebugSessionRequestExample'
  responses:
    GetExpectedConfigVersionResponse:
      description: Response body for retrieving the expected config version of the control plane.
      content:
        application/json:
          schema:
            type: object
            properties:
              expected_config_version:
                description: The expected configuration version.
                type: string
              created_at:
                description: Date the control plane configuration version was created.
                type: integer
            required:
              - expected_config_version
    ListConfigStoresResponse:
      description: List of Config Stores
      content:
        application/json:
          schema:
            type: object
            properties:
              meta:
                $ref: '#/components/schemas/CursorMeta'
              data:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigStore'
            required:
              - data
              - meta
            title: ListConfigStoresResponse
          examples:
            Config Stores:
              value:
                data:
                  - id: e7a4f6c0-5777-4a37-bcb9-2d37d3b362ee
                    name: Config Store
                    created_at: '2023-01-01T00:00:00.000Z'
                    updated_at: '2023-01-01T00:00:00.000Z'
                meta:
                  page:
                    size: 1
                    previous: null
                    next: '/config-stores?page[after]=dXVpZC01'
    ListConfigStoreSecretsResponse:
      description: List of Config Store Secrets
      content:
        application/json:
          schema:
            type: object
            properties:
              meta:
                $ref: '#/components/schemas/CursorMeta'
              data:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigStoreSecret'
            required:
              - data
              - meta
            title: ListConfigStoreSecretsResponse
          examples:
            Config Store Secrets:
              value:
                data:
                  - key: ConfigStoreSecretKey
                    value: ConfigStoreSecretValue
                    created_at: '2023-01-01T00:00:00.000Z'
                    updated_at: '2023-01-01T00:00:00.000Z'
                meta:
                  page:
                    size: 1
                    previous: null
                    next: '/config-stores/e7a4f6c0-5777-4a37-bcb9-2d37d3b362ee/secrets?page[after]=dXVpZC01'
    ConfigStoreResponse:
      description: Config Store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigStore'
          examples:
            Create Config Store Response:
              $ref: '#/components/examples/ConfigStoreExample'
    ConfigStoreSecretResponse:
      description: Config Store Secret
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigStoreSecret'
          examples:
            Create Config Store Secret Response:
              $ref: '#/components/examples/ConfigStoreSecretExample'
    ConfigStoreUnauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/UnauthorizedExample'
    ConfigStoreSecretUnauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/UnauthorizedExample'
    ConfigStoreNotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
          examples:
            NotFoundExample:
              $ref: '#/components/examples/NotFoundExample'
    ConfigStoreSecretNotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
          examples:
            NotFoundExample:
              $ref: '#/components/examples/NotFoundExample'
    DebugSessionUnauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/UnauthorizedExample'
    ListDebugSessionsResponse:
      description: List of DebugSessions
      content:
        application/json:
          schema:
            type: object
            properties:
              meta:
                $ref: '#/components/schemas/CursorMeta'
              data:
                type: array
                items:
                  $ref: '#/components/schemas/DebugSession'
            required:
              - data
              - meta
            title: ListDebugSessionsResponse
          examples:
            Debug Sessions:
              value:
                data:
                  - id: e7a4f6c0-5777-4a37-bcb9-2d37d3b362ee
                    max_samples: 10
                    duration_secs: 300
                    created_at: '2024-10-01T20:00:00.000Z'
                    updated_at: '2024-10-01T20:00:00.000Z'
                meta:
                  page:
                    size: 10
                    next: null
                    previous: null
    DebugSessionResponse:
      description: Debug Session Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DebugSession'
          examples:
            Create Debug Session Response:
              $ref: '#/components/examples/DebugSessionExample'
    DebugSessionStopResponse:
      description: Debug Session Stop Response
      content:
        application/json:
          schema:
            type: object
    HTTP401Error:
      description: Unauthorized
      content:
        application/json:
          examples:
            DuplicateApiKey:
              summary: Duplicate API key found
              value:
                message: Duplicate API key found
                status: 401
            InvalidAuthCred:
              summary: Invalid authentication credentials
              value:
                message: Unauthorized
                status: 401
            NoAPIKey:
              summary: No API key found
              value:
                message: No API key found in request
                status: 401
          schema:
            $ref: '#/components/schemas/GatewayUnauthorizedError'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/ForbiddenExample'
    UnsupportedMediaType:
      description: Unsupported Media Type
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/UnsupportedMediaTypeError'
          examples:
            UnsupportedMediaTypeExample:
              $ref: '#/components/examples/UnsupportedMediaTypeExample'
  securitySchemes:
    konnectAccessToken:
      type: http
      scheme: bearer
      description: The Konnect access token is meant to be used by the Konnect dashboard and the decK CLI to authenticate with.
    personalAccessToken:
      type: http
      scheme: bearer
      description: The personal access token is meant to be used as an alternative to basic-auth when accessing Konnect via APIs. You can generate a Personal Access Token (PAT) from the personal access token page in the Konnect dashboard.
tags:
  - description: DP Nodes
    name: DP Nodes
  - description: Config Stores
    name: Config Stores
  - description: Config Store Secrets
    name: Config Store Secrets
  - description: Debug Sessions
    name: Debug Sessions
  - name: CustomPlugins
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: 'https://docs.konghq.com'
security:
  - konnectAccessToken: []
  - personalAccessToken: []
