openapi: 3.0.3
info:
  title: Konnect Application Auth Strategies
  version: 2.0.0
  description: The API for Kong Konnect Portal Application Configuration
  contact:
    name: Kong
    url: https://cloud.konghq.com
servers:
  - url: https://us.api.konghq.com/v2
    description: US Region Base URL
  - url: https://eu.api.konghq.com/v2
    description: EU Region Base URL
  - url: https://au.api.konghq.com/v2
    description: AU Region Base URL
tags: []
paths: {}
components:
  schemas:
    PublishStatusFilter:
      title: PublishStatusFilter
      description: Filters on the given publish status
      oneOf:
        - $ref: '#/components/schemas/StringFieldEqualsFilter'
        - $ref: '#/components/schemas/StringFieldOEQFilter'
        - $ref: '#/components/schemas/StringFieldNEQFilter'
      x-examples:
        example-1: published
        example-2:
          eq: unpublished
        example-3:
          neq: unpublished
    PortalProductVersionFilters:
      title: PortalProductVersionFilters
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/UuidFieldFilter'
        publish_status:
          $ref: '#/components/schemas/PublishStatusFilter'
        product_version_id:
          $ref: '#/components/schemas/UuidFieldFilter'
        created_at:
          $ref: '#/components/schemas/DateTimeFieldFilter'
        updated_at:
          $ref: '#/components/schemas/DateTimeFieldFilter'
        auth_strategy_ids:
          $ref: '#/components/schemas/UuidFieldFilter'
        application_registration_enabled:
          $ref: '#/components/schemas/BooleanFieldFilter'
        auto_approve_registration:
          $ref: '#/components/schemas/BooleanFieldFilter'
        deprecated:
          $ref: '#/components/schemas/BooleanFieldFilter'
    PortalProductVersionPublishStatus:
      type: string
      description: Publication status of the API product version on the portal
      enum:
        - published
        - unpublished
    ApplicationRegistrationEnabled:
      type: boolean
      description: >-
        Enables the application registration on this portal for the api product
        version
    AutoApproveRegistration:
      type: boolean
      description: >-
        Enables the application registration auto approval on this portal for
        the api product version
    PortalProductVersionDeprecated:
      type: boolean
      description: Deprecates the api product version on the portal
    AuthStrategyIDs:
      description: A list of authentication strategy IDs
      type: array
      minItems: 0
      maxItems: 1
      items:
        $ref: '#/components/schemas/UUID_RW'
    CreatePortalProductVersionPayload:
      title: CreatePortalProductVersionPayload
      type: object
      additionalProperties: false
      properties:
        publish_status:
          $ref: '#/components/schemas/PortalProductVersionPublishStatus'
        product_version_id:
          $ref: '#/components/schemas/UUID_RW'
        auth_strategy_ids:
          $ref: '#/components/schemas/AuthStrategyIDs'
        application_registration_enabled:
          $ref: '#/components/schemas/ApplicationRegistrationEnabled'
        auto_approve_registration:
          $ref: '#/components/schemas/AutoApproveRegistration'
        deprecated:
          $ref: '#/components/schemas/PortalProductVersionDeprecated'
      required:
        - publish_status
        - application_registration_enabled
        - auto_approve_registration
        - product_version_id
        - deprecated
        - auth_strategy_ids
    UpdatePortalProductVersionPayload:
      title: UpdatePortalProductVersionPayload
      type: object
      additionalProperties: false
      properties:
        publish_status:
          $ref: '#/components/schemas/PortalProductVersionPublishStatus'
        auth_strategy_ids:
          $ref: '#/components/schemas/AuthStrategyIDs'
        application_registration_enabled:
          $ref: '#/components/schemas/ApplicationRegistrationEnabled'
        auto_approve_registration:
          $ref: '#/components/schemas/AutoApproveRegistration'
        deprecated:
          $ref: '#/components/schemas/PortalProductVersionDeprecated'
    PortalProductVersion:
      title: PortalProductVersion
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        publish_status:
          $ref: '#/components/schemas/PortalProductVersionPublishStatus'
        product_version_id:
          $ref: '#/components/schemas/UUID_RW'
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
        auth_strategy_ids:
          $ref: '#/components/schemas/AuthStrategyIDs'
        application_registration_enabled:
          $ref: '#/components/schemas/ApplicationRegistrationEnabled'
        auto_approve_registration:
          $ref: '#/components/schemas/AutoApproveRegistration'
        deprecated:
          $ref: '#/components/schemas/PortalProductVersionDeprecated'
      required:
        - id
        - publish_status
        - application_registration_enabled
        - auto_approve_registration
        - product_version_id
        - deprecated
        - auth_strategy_ids
        - created_at
        - updated_at
    ListPortalProductVersions:
      title: ListPortalProductVersions
      type: object
      additionalProperties: false
      required:
        - data
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PortalProductVersion'
        meta:
          $ref: '#/components/schemas/PaginatedMeta'
    DcrConfigPropertyInitialClientId:
      title: DcrConfigPropertyInitialClientId
      type: string
      maxLength: 256
      description: >
        This ID should be copied from your identity provider's settings after
        you create a client

        and assign it as the management client for DCR for this developer portal
    DcrConfigPropertyInitialClientSecret:
      title: DcrConfigPropertyInitialClientSecret
      type: string
      maxLength: 256
      description: >
        This secret should be copied from your identity provider's settings
        after you create a client

        and assign it as the management client for DCR for this developer portal
    DcrConfigPropertyDcrToken:
      title: DcrConfigPropertyInitialDcrToken
      type: string
      maxLength: 256
      description: >
        This secret should be copied from your identity provider's settings
        after you create a client

        and assign it as the management client for DCR for this developer portal
    DcrConfigPropertyInitialClientAudience:
      title: DcrConfigPropertyInitialClientAudience
      type: string
      maxLength: 256
      nullable: true
      description: >
        This is the audience value used for the initial client.

        If using a custom domain on Auth0, this must be set as to the Auth0
        Management API audience value.

        If left blank, the issuer will be used instead.
    DcrConfigPropertyApiKey:
      title: DcrConfigPropertyApiKey
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 12
      maxLength: 256
      description: >
        This is the API Key that will be sent with each HTTP request to the
        custom DCR server. It can be

        verified on the server to ensure that incoming requests are coming from
        Konnect.
    DcrConfigAuth0InResponse:
      title: DcrConfigAuth0InResponse
      type: object
      additionalProperties: false
      required:
        - initial_client_id
        - initial_client_audience
        - use_developer_managed_scopes
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_audience:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientAudience'
        use_developer_managed_scopes:
          type: boolean
    CreateDcrConfigAuth0InRequest:
      title: DcrConfigAuth0InRequest
      type: object
      additionalProperties: false
      required:
        - initial_client_id
        - initial_client_secret
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
        initial_client_audience:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientAudience'
        use_developer_managed_scopes:
          type: boolean
    UpdateDcrConfigAuth0InRequest:
      title: DcrConfigAuth0InRequest
      type: object
      additionalProperties: false
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
        initial_client_audience:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientAudience'
        use_developer_managed_scopes:
          type: boolean
    DcrConfigAzureAdInResponse:
      title: DcrConfigAzureAdInResponse
      type: object
      additionalProperties: false
      required:
        - initial_client_id
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
    CreateDcrConfigAzureAdInRequest:
      title: DcrConfigAzureAdInRequest
      type: object
      additionalProperties: false
      required:
        - initial_client_id
        - initial_client_secret
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
    UpdateDcrConfigAzureAdInRequest:
      title: DcrConfigAzureAdInRequest
      type: object
      additionalProperties: false
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
    DcrConfigCurityInResponse:
      title: DcrConfigCurityInResponse
      type: object
      additionalProperties: false
      required:
        - initial_client_id
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
    CreateDcrConfigCurityInRequest:
      title: DcrConfigCurityInRequest
      type: object
      additionalProperties: false
      required:
        - initial_client_id
        - initial_client_secret
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
    UpdateDcrConfigCurityInRequest:
      title: DcrConfigCurityInRequest
      type: object
      additionalProperties: false
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
    DcrConfigOktaInResponse:
      title: DcrConfigOktaInResponse
      type: object
      additionalProperties: false
    CreateDcrConfigOktaInRequest:
      title: DcrConfigOktaInRequest
      type: object
      additionalProperties: false
      required:
        - dcr_token
      properties:
        dcr_token:
          $ref: '#/components/schemas/DcrConfigPropertyDcrToken'
    UpdateDcrConfigOktaInRequest:
      title: DcrConfigOktaInRequest
      type: object
      additionalProperties: false
      properties:
        dcr_token:
          $ref: '#/components/schemas/DcrConfigPropertyDcrToken'
    DcrConfigHttpInResponse:
      title: DcrConfigHttpInResponse
      type: object
      additionalProperties: false
      required:
        - dcr_base_url
      properties:
        dcr_base_url:
          type: string
          format: url
    DcrConfigHttpInResponseWithApiKey:
      title: DcrConfigHttpInResponseWithApiKey
      type: object
      additionalProperties: false
      required:
        - dcr_base_url
        - api_key
      properties:
        dcr_base_url:
          type: string
          format: url
        api_key:
          $ref: '#/components/schemas/DcrConfigPropertyApiKey'
    CreateDcrConfigHttpInRequest:
      title: CreateDcrConfigHttpInRequest
      type: object
      additionalProperties: false
      required:
        - dcr_base_url
        - api_key
      properties:
        dcr_base_url:
          $ref: '#/components/schemas/DcrBaseUrl'
        api_key:
          $ref: '#/components/schemas/DcrConfigPropertyApiKey'
    UpdateDcrConfigHttpInRequest:
      title: CreateDcrConfigHttpInRequest
      type: object
      additionalProperties: false
      properties:
        dcr_base_url:
          $ref: '#/components/schemas/DcrBaseUrl'
        api_key:
          $ref: '#/components/schemas/DcrConfigPropertyApiKey'
    DcrProviderType:
      title: DcrProviderType
      type: string
      enum:
        - auth0
        - azureAd
        - curity
        - okta
        - http
    DcrProviderBase:
      type: object
      title: DcrProviderBase
      description: Properties common to all DCR Providers.
      additionalProperties: false
      required:
        - id
        - name
        - display_name
        - provider_type
        - issuer
        - active
        - dcr_config
        - created_at
        - updated_at
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
          maxLength: 256
        display_name:
          type: string
          maxLength: 256
        provider_type:
          $ref: '#/components/schemas/DcrProviderType'
        issuer:
          type: string
          format: url
          maxLength: 256
        active:
          readOnly: true
          type: boolean
          description: At least one active auth strategy is using this DCR provider.
        dcr_config:
          type: object
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
    DcrProviderAuth0:
      title: DcrProviderAuth0
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - auth0
        dcr_config:
          $ref: '#/components/schemas/DcrConfigAuth0InResponse'
    DcrProviderAzureAd:
      title: DcrProviderAzureAd
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - azureAd
        dcr_config:
          $ref: '#/components/schemas/DcrConfigAzureAdInResponse'
    DcrProviderCurity:
      title: DcrProviderCurity
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - curity
        dcr_config:
          $ref: '#/components/schemas/DcrConfigCurityInResponse'
    DcrProviderOkta:
      title: DcrProviderOkta
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - okta
        dcr_config:
          $ref: '#/components/schemas/DcrConfigOktaInResponse'
    DcrProviderHttp:
      title: DcrProviderHttp
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - http
        dcr_config:
          $ref: '#/components/schemas/DcrConfigHttpInResponse'
    DcrProviderHttpWithApiKey:
      title: DcrProviderHttpWithApiKey
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - http
        dcr_config:
          $ref: '#/components/schemas/DcrConfigHttpInResponseWithApiKey'
    CreateDcrProviderResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/DcrProviderBase'
        - discriminator:
            propertyName: provider_type
          type: object
          oneOf:
            - $ref: '#/components/schemas/DcrProviderAuth0'
            - $ref: '#/components/schemas/DcrProviderAzureAd'
            - $ref: '#/components/schemas/DcrProviderCurity'
            - $ref: '#/components/schemas/DcrProviderOkta'
            - $ref: '#/components/schemas/DcrProviderHttpWithApiKey'
    DcrProviderResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/DcrProviderBase'
        - discriminator:
            propertyName: provider_type
          type: object
          oneOf:
            - $ref: '#/components/schemas/DcrProviderAuth0'
            - $ref: '#/components/schemas/DcrProviderAzureAd'
            - $ref: '#/components/schemas/DcrProviderCurity'
            - $ref: '#/components/schemas/DcrProviderOkta'
            - $ref: '#/components/schemas/DcrProviderHttp'
    CreateDcrProviderRequestBase:
      type: object
      title: CreateDcrProviderRequestBase
      description: A DCR provider payload.
      additionalProperties: false
      required:
        - name
        - display_name
        - provider_type
        - issuer
        - dcr_config
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 256
        display_name:
          type: string
          minLength: 1
          maxLength: 256
        provider_type:
          $ref: '#/components/schemas/DcrProviderType'
        issuer:
          type: string
          format: url
          maxLength: 256
        dcr_config:
          type: object
    CreateDcrProviderRequestAuth0:
      title: CreateDcrProviderRequestAuth0
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - auth0
        dcr_config:
          $ref: '#/components/schemas/CreateDcrConfigAuth0InRequest'
    CreateDcrProviderRequestAzureAd:
      title: CreateDcrProviderRequestAzureAd
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - azureAd
        dcr_config:
          $ref: '#/components/schemas/CreateDcrConfigAzureAdInRequest'
    CreateDcrProviderRequestCurity:
      title: CreateDcrProviderRequestCurity
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - curity
        dcr_config:
          $ref: '#/components/schemas/CreateDcrConfigCurityInRequest'
    CreateDcrProviderRequestOkta:
      title: CreateDcrProviderRequestOkta
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - okta
        dcr_config:
          $ref: '#/components/schemas/CreateDcrConfigOktaInRequest'
    CreateDcrProviderRequestHttp:
      title: CreateDcrProviderRequestHttp
      type: object
      required:
        - provider_type
        - dcr_config
      properties:
        provider_type:
          type: string
          enum:
            - http
        dcr_config:
          $ref: '#/components/schemas/CreateDcrConfigHttpInRequest'
    CreateDcrProviderRequest:
      title: CreateDcrProviderRequest
      description: A DCR provider to create.
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateDcrProviderRequestBase'
        - discriminator:
            propertyName: provider_type
          type: object
          oneOf:
            - $ref: '#/components/schemas/CreateDcrProviderRequestAuth0'
            - $ref: '#/components/schemas/CreateDcrProviderRequestAzureAd'
            - $ref: '#/components/schemas/CreateDcrProviderRequestCurity'
            - $ref: '#/components/schemas/CreateDcrProviderRequestOkta'
            - $ref: '#/components/schemas/CreateDcrProviderRequestHttp'
    UpdateDcrProviderRequest:
      type: object
      title: UpdateDcrProviderRequest
      description: >-
        A set of updates to a DCR provider. The provider_type cannot be updated
        after creation.
      additionalProperties: false
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 256
        display_name:
          type: string
          minLength: 1
          maxLength: 256
        issuer:
          type: string
          format: url
          maxLength: 256
        dcr_config:
          anyOf:
            - $ref: '#/components/schemas/UpdateDcrConfigAuth0InRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigAzureAdInRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigCurityInRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigOktaInRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigHttpInRequest'
    ListDcrProvidersResponse:
      title: ListDcrProvidersResponse
      type: object
      additionalProperties: false
      required:
        - data
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DcrProviderResponse'
        meta:
          $ref: '#/components/schemas/PaginatedMeta'
    VerifyDcrProviderResponse:
      title: VerifyDcrProviderResponse
      type: object
      additionalProperties: false
      required:
        - status
        - errors
      properties:
        status:
          type: string
          enum:
            - success
            - failed
        errors:
          nullable: true
          type: array
          items:
            type: string
    RefreshDcrProviderApiKeyResponse:
      title: RefreshDcrProviderApiKeyResponse
      oneOf:
        - $ref: '#/components/schemas/DcrProviderHttpWithApiKey'
    AuthStrategyType:
      title: AuthStrategyType
      type: string
      enum:
        - key_auth
        - openid_connect
    AppAuthStrategyResponseBase:
      title: AppAuthStrategyResponseBase
      type: object
      required:
        - id
        - name
        - display_name
        - strategy_type
        - configs
        - active
        - dcr_provider
        - created_at
        - updated_at
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
          maxLength: 256
        display_name:
          type: string
          maxLength: 256
        strategy_type:
          $ref: '#/components/schemas/AuthStrategyType'
        configs:
          type: object
        active:
          type: boolean
          description: At least one published product version is using this auth strategy.
        dcr_provider:
          nullable: true
          type: object
          additionalProperties: false
          required:
            - id
            - name
            - display_name
            - provider_type
          properties:
            id:
              $ref: '#/components/schemas/UUID'
            name:
              type: string
            display_name:
              type: string
            provider_type:
              $ref: '#/components/schemas/DcrProviderType'
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
    CreateAppAuthStrategyRequestBase:
      title: CreateAppAuthStrategyRequestBase
      type: object
      required:
        - name
        - display_name
        - strategy_type
        - configs
      properties:
        name:
          type: string
          maxLength: 256
        display_name:
          type: string
          maxLength: 256
        strategy_type:
          $ref: '#/components/schemas/AuthStrategyType'
        configs:
          type: object
        dcr_provider_id:
          nullable: true
          type: string
          format: uuid
    AppAuthStrategyConfigKeyAuth:
      title: AppAuthStrategyConfigKeyAuth
      type: object
      additionalProperties: false
      properties:
        key_names:
          type: array
          maxItems: 10
          minItems: 1
          items:
            type: string
            maxLength: 256
          description: >-
            The names of the headers containing the API key. You can specify
            multiple header names.
    AppAuthStrategyConfigOpenIDConnect:
      title: AppAuthStrategyConfigOpenIDConnect
      type: object
      additionalProperties: true
      required:
        - issuer
        - credential_claim
        - scopes
        - auth_methods
      properties:
        issuer:
          type: string
          format: url
          maxLength: 256
        credential_claim:
          type: array
          maxItems: 10
          items:
            type: string
            maxLength: 128
        scopes:
          type: array
          maxItems: 50
          items:
            type: string
            maxLength: 128
        auth_methods:
          type: array
          maxItems: 10
          items:
            type: string
            maxLength: 64
    AppAuthStrategyKeyAuth:
      title: AppAuthStrategyKeyAuth
      type: object
      required:
        - strategy_type
        - configs
      properties:
        strategy_type:
          type: string
          enum:
            - key_auth
        configs:
          type: object
          additionalProperties: false
          required:
            - key-auth
          properties:
            key-auth:
              $ref: '#/components/schemas/AppAuthStrategyConfigKeyAuth'
    AppAuthStrategyOpenIDConnect:
      title: AppAuthStrategyOpenIDConnect
      type: object
      required:
        - strategy_type
        - configs
      properties:
        strategy_type:
          type: string
          enum:
            - openid_connect
        configs:
          type: object
          additionalProperties: false
          required:
            - openid-connect
          properties:
            openid-connect:
              $ref: '#/components/schemas/AppAuthStrategyConfigOpenIDConnect'
    CreateAppAuthStrategyRequest:
      title: CreateAppAuthStrategyRequest
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateAppAuthStrategyRequestBase'
        - discriminator:
            propertyName: strategy_type
          type: object
          oneOf:
            - $ref: '#/components/schemas/AppAuthStrategyKeyAuth'
            - $ref: '#/components/schemas/AppAuthStrategyOpenIDConnect'
    AppAuthStrategy:
      title: AppAuthStrategy
      type: object
      allOf:
        - $ref: '#/components/schemas/AppAuthStrategyResponseBase'
        - discriminator:
            propertyName: strategy_type
          type: object
          oneOf:
            - $ref: '#/components/schemas/AppAuthStrategyKeyAuth'
            - $ref: '#/components/schemas/AppAuthStrategyOpenIDConnect'
    CreateAppAuthStrategyResponse:
      $ref: '#/components/schemas/AppAuthStrategy'
    UpdateAppAuthStrategyRequest:
      title: UpdateAppAuthStrategyRequest
      allOf:
        - type: object
          additionalProperties: false
          properties:
            name:
              type: string
              maxLength: 256
            display_name:
              type: string
              maxLength: 256
            strategy_type:
              $ref: '#/components/schemas/AuthStrategyType'
            configs:
              type: object
            dcr_provider_id:
              nullable: true
              type: string
              format: uuid
        - anyOf:
            - allOf:
                - type: object
                  required:
                    - strategy_type
                  properties:
                    strategy_type:
                      $ref: '#/components/schemas/AuthStrategyType'
                - discriminator:
                    propertyName: strategy_type
                  type: object
                  oneOf:
                    - $ref: '#/components/schemas/AppAuthStrategyKeyAuth'
                    - $ref: '#/components/schemas/AppAuthStrategyOpenIDConnect'
            - anyOf:
                - type: object
                  properties:
                    configs:
                      type: object
                      additionalProperties: false
                      required:
                        - key-auth
                      properties:
                        key-auth:
                          $ref: '#/components/schemas/AppAuthStrategyConfigKeyAuth'
                - type: object
                  properties:
                    configs:
                      type: object
                      additionalProperties: false
                      required:
                        - openid-connect
                      properties:
                        openid-connect:
                          $ref: >-
                            #/components/schemas/AppAuthStrategyConfigOpenIDConnect
            - type: object
    UpdateAppAuthStrategyResponse:
      $ref: '#/components/schemas/AppAuthStrategy'
    GetAppAuthStrategyResponse:
      $ref: '#/components/schemas/AppAuthStrategy'
    ListAppAuthStrategiesResponse:
      title: ListAppAuthStrategiesResponse
      type: object
      additionalProperties: false
      required:
        - data
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AppAuthStrategy'
        meta:
          $ref: '#/components/schemas/PaginatedMeta'
    DcrBaseUrl:
      type: string
      format: url
      maxLength: 256
    UUID:
      type: string
      format: uuid
      example: 5f9fd312-a987-4628-b4c5-bb4f4fddd5f7
      description: Contains a unique identifier used by the API for this resource.
      readOnly: true
    CreatedAt:
      type: string
      format: date-time
      example: '2022-11-04T20:10:06.927Z'
      description: An ISO-8601 timestamp representation of entity creation date.
      readOnly: true
    UpdatedAt:
      type: string
      format: date-time
      example: '2022-11-04T20:10:06.927Z'
      description: An ISO-8601 timestamp representation of entity update date.
      readOnly: true
    PageMeta:
      type: object
      description: >-
        Contains pagination query parameters and the total number of objects
        returned.
      required:
        - number
        - size
        - total
      properties:
        number:
          type: number
          example: 1
        size:
          type: number
          example: 10
        total:
          type: number
          example: 100
    PaginatedMeta:
      type: object
      title: PaginatedMeta
      description: returns the pagination information
      properties:
        page:
          $ref: '#/components/schemas/PageMeta'
      required:
        - page
    BaseError:
      type: object
      title: Error
      description: standard error
      required:
        - status
        - title
        - instance
        - detail
      properties:
        status:
          type: integer
          description: >
            The HTTP status code of the error. Useful when passing the response

            body to child properties in a frontend UI. Must be returned as an
            integer.
          readOnly: true
        title:
          type: string
          description: |
            A short, human-readable summary of the problem. It should not
            change between occurences of a problem, except for localization.
            Should be provided as "Sentence case" for direct use in the UI.
          readOnly: true
        type:
          type: string
          description: The error type.
          readOnly: true
        instance:
          type: string
          description: |
            Used to return the correlation ID back to the user, in the format
            kong:trace:<correlation_id>. This helps us find the relevant logs
            when a customer reports an issue.
          readOnly: true
        detail:
          type: string
          description: >
            A human readable explanation specific to this occurence of the
            problem.

            This field may contain request/entity data to help the user
            understand

            what went wrong. Enclose variable values in square brackets. Should
            be

            provided as "Sentence case" for direct use in the UI.
          readOnly: true
    InvalidRules:
      description: invalid parameters rules
      type: string
      readOnly: true
      nullable: true
      enum:
        - required
        - enum
        - min_length
        - max_length
        - min_digits
        - min_lowercase
        - min_uppercase
        - min_symbols
        - is_array
        - is_base64
        - is_boolean
        - is_date_time
        - is_integer
        - is_null
        - is_number
        - is_object
        - is_string
        - is_uuid
        - unknown_property
        - is_label
        - matches_regex
    InvalidParameterChoiceItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          $ref: '#/components/schemas/InvalidRules'
        reason:
          type: string
          example: is a required field
          readOnly: true
        choices:
          type: array
          uniqueItems: true
          nullable: true
          items: {}
          readOnly: true
      required:
        - field
        - reason
    InvalidParameterDependentItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          readOnly: true
          nullable: true
          enum:
            - dependent_fields
        reason:
          type: string
          example: is a required field
          readOnly: true
        dependents:
          type: array
          uniqueItems: true
          nullable: true
          items: {}
          readOnly: true
      required:
        - field
        - rule
        - reason
        - dependents
    InvalidParameters:
      type: array
      nullable: false
      uniqueItems: true
      minItems: 1
      description: invalid parameters
      items:
        oneOf:
          - $ref: '#/components/schemas/InvalidParameterChoiceItem'
          - $ref: '#/components/schemas/InvalidParameterDependentItem'
    BadRequestError:
      type: object
      required:
        - invalid_parameters
      properties:
        status:
          example: 400
        title:
          example: Bad Request
        type:
          example: https://httpstatuses.com/400
        instance:
          example: kong:trace:1234567890
        detail:
          example: Invalid request body
        invalid_parameters:
          $ref: '#/components/schemas/InvalidParameters'
      allOf:
        - $ref: '#/components/schemas/BaseError'
    UnauthorizedError:
      type: object
      properties:
        status:
          example: 401
        title:
          example: Unauthorized
        type:
          example: https://httpstatuses.com/401
        instance:
          example: kong:trace:1234567890
        detail:
          example: Invalid credentials
      allOf:
        - $ref: '#/components/schemas/BaseError'
    ForbiddenError:
      type: object
      properties:
        status:
          example: 403
        title:
          example: Forbidden
        type:
          example: https://httpstatuses.com/403
        instance:
          example: kong:trace:1234567890
        detail:
          example: Forbidden
      allOf:
        - $ref: '#/components/schemas/BaseError'
    NotFoundError:
      type: object
      properties:
        status:
          example: 404
        title:
          example: Not Found
        type:
          example: https://httpstatuses.com/404
        instance:
          example: kong:trace:1234567890
        detail:
          example: Not found
      allOf:
        - $ref: '#/components/schemas/BaseError'
    StringFieldEqualsFilter:
      title: StringFieldEqualsFilter
      description: Filters on the given string field value by exact match.
      oneOf:
        - type: string
        - type: object
          title: StringFieldEqualsComparison
          additionalProperties: false
          properties:
            eq:
              type: string
          required:
            - eq
      x-examples:
        example-1: equals-some-value
        example-2:
          eq: some-value
    StringFieldContainsFilter:
      title: StringFieldContainsFilter
      description: Filters on the given string field value by fuzzy match.
      type: object
      additionalProperties: false
      properties:
        contains:
          type: string
      required:
        - contains
      x-examples:
        example-1:
          contains: some-value
    StringFieldOContainsFilter:
      title: StringFieldOContainsFilter
      description: >-
        Returns entities that fuzzy-match any of the comma-delimited phrases in
        the filter string.
      type: object
      additionalProperties: false
      properties:
        ocontains:
          type: string
      required:
        - ocontains
      x-examples:
        example-1:
          ocontains: this-value,or-that-value
    StringFieldOEQFilter:
      title: StringFieldOEQFilter
      description: >-
        Returns entities that exact match any of the comma-delimited phrases in
        the filter string.
      type: object
      additionalProperties: false
      properties:
        oeq:
          type: string
      required:
        - oeq
      x-examples:
        example-1:
          oeq: some-value,some-other-value
    StringFieldNEQFilter:
      title: StringFieldNEQFilter
      description: Filters on the given string field value by exact match inequality.
      type: object
      additionalProperties: false
      properties:
        neq:
          type: string
      required:
        - neq
      x-examples:
        example-1:
          neq: not-this-value
    UuidFieldFilter:
      title: UuidFieldFilter
      description: Filters on the given UUID field value by exact match.
      oneOf:
        - $ref: '#/components/schemas/StringFieldEqualsFilter'
        - $ref: '#/components/schemas/StringFieldOEQFilter'
        - $ref: '#/components/schemas/StringFieldNEQFilter'
      x-examples:
        example-1: 3bbfd3a-e9ab-48a9-9881-ed589e4615d1
        example-2:
          eq: 3bbfd3a-e9ab-48a9-9881-ed589e4615d1
        example-3:
          oeq: 3bbfd3a-e9ab-48a9-9881-ed589e4615d1
        example-4:
          neq: 3bbfd3a-e9ab-48a9-9881-ed589e4615d1
    DateTimeFieldFilter:
      title: DateTimeFieldFilter
      description: Filters on the given datetime (RFC-3339) field value.
      oneOf:
        - type: string
          format: date-time
          description: Value strictly equals given RFC-3339 formatted timestamp in UTC
          example: '2022-03-30T07:20:50Z'
        - type: object
          title: DateTimeFieldEqualsFilter
          additionalProperties: false
          properties:
            eq:
              type: string
              format: date-time
              description: Value strictly equals given RFC-3339 formatted timestamp in UTC
              example: '2022-03-30T07:20:50Z'
          required:
            - eq
        - type: object
          title: DateTimeFieldLTFilter
          additionalProperties: false
          properties:
            lt:
              type: string
              format: date-time
              description: Value is less than the given RFC-3339 formatted timestamp in UTC
              example: '2022-03-30T07:20:50Z'
          required:
            - lt
        - type: object
          title: DateTimeFieldLTEFilter
          additionalProperties: false
          properties:
            lte:
              type: string
              format: date-time
              description: >-
                Value is less than or equal to the given RFC-3339 formatted
                timestamp in UTC
              example: '2022-03-30T07:20:50Z'
          required:
            - lte
        - type: object
          title: DateTimeFieldGTFilter
          additionalProperties: false
          properties:
            lt:
              type: string
              format: date-time
              description: >-
                Value is greater than the given RFC-3339 formatted timestamp in
                UTC
              example: '2022-03-30T07:20:50Z'
          required:
            - gt
        - type: object
          title: DateTimeFieldGTEFilter
          additionalProperties: false
          properties:
            lte:
              type: string
              format: date-time
              description: >-
                Value is greater than or equal to the given RFC-3339 formatted
                timestamp in UTC
              example: '2022-03-30T07:20:50Z'
          required:
            - gte
      x-examples:
        datetime_field_1: '2022-03-30T07:20:50Z'
        datetime_field_2:
          eq: '2022-03-30T07:20:50Z'
        datetime_field_3:
          lt: '2022-03-30T07:20:50Z'
        datetime_field_4:
          lte: '2022-03-30T07:20:50Z'
        datetime_field_5:
          gt: '2022-03-30T07:20:50Z'
        datetime_field_6:
          gte: '2022-03-30T07:20:50Z'
    BooleanFieldFilter:
      title: BooleanFieldFilter
      description: Filter by a boolean value (true/false).
      type: boolean
      x-examples:
        example-1: true
    UUID_RW:
      type: string
      format: uuid
      example: 5f9fd312-a987-4628-b4c5-bb4f4fddd5f7
      description: Contains a unique identifier used by the API for this resource.
  examples:
    DcrProviderOktaCreateRequest:
      summary: DCR Provider Okta Create Request
      value:
        name: DCR Okta 1 - Segment A
        display_name: Client Credentials
        provider_type: okta
        issuer: https://my-issuer.okta.com/default
        dcr_config:
          dcr_token: abc123xyz098!
    DcrProviderAuth0CreateRequest:
      summary: DCR Provider Auth0 Create Request
      value:
        name: DCR Auth0 1 - Segment A
        display_name: Client Credentials 2
        provider_type: auth0
        issuer: https://my-issuer.auth0.com/api/v2/
        dcr_config:
          initial_client_id: abc123
          initial_client_secret: abc123xyz098!
          initial_client_audience: https://my-custom-domain.com/api/v2/
    DcrProviderAzureAdCreateRequest:
      summary: DCR Provider AzureAd Create Request
      value:
        name: DCR Azure 1 - Segment A
        display_name: Client Credentials 3
        provider_type: azureAd
        issuer: https://sts.windows.net/my-tenant
        dcr_config:
          initial_client_id: abc123
          initial_client_secret: abc123xyz098!
    DcrProviderCurityCreateRequest:
      summary: DCR Provider Curity Create Request
      value:
        name: DCR Curity 1 - Segment A
        display_name: Client Credentials 4
        provider_type: curity
        issuer: >-
          https://my-curity-instance.com/oauth/v2/oauth-anonymous/.well-known/openid-configuration
        dcr_config:
          initial_client_id: abc123
          initial_client_secret: abc123xyz098!
    DcrProviderHttpCreateRequest:
      summary: DCR Provider HTTP Create Request
      value:
        name: DCR HTTP 1 - Segment A
        display_name: Client Credentials 5
        provider_type: http
        issuer: https://my-issuer-server.com
        dcr_config:
          dcr_base_url: https://my-http-dcr-server.com/v1/dcr
          api_key: gYmrbDfu_7PTsZWH
    DcrProviderOktaUpdateRequest:
      summary: DCR Provider Create Request
      value:
        name: DCR Okta 1 - Segment A
        display_name: Client Credentials
        issuer: https://my-issuer.okta.com/default
    DcrProviderOktaResponse:
      summary: DCR Provider Response
      value:
        id: 93f8380e-7798-4566-99e3-2edf2b57d289
        name: DCR Okta 1 - Segment A
        display_name: Client Credentials
        provider_type: okta
        issuer: https://my-issuer.okta.com/default
        active: true
        dcr_config: {}
        created_at: '2023-01-01T00:00:00.000Z'
        updated_at: '2023-01-01T00:00:00.000Z'
    ListDcrProvidersResponse:
      summary: List DCR Providers Response
      value:
        data:
          - id: 93f8380e-7798-4566-99e3-2edf2b57d289
            name: DCR Okta 1 - Segment A
            display_name: Client Credentials
            provider_type: okta
            issuer: https://my-issuer.okta.com/default
            active: true
            dcr_config: {}
            created_at: '2023-01-01T00:00:00.000Z'
            updated_at: '2023-01-01T00:00:00.000Z'
        meta:
          page:
            number: 1
            size: 1
            total: 10
    VerifyDcrProviderResponseSuccess:
      summary: Verify DCR Provider Success Response
      value:
        status: success
        errors: null
    VerifyDcrProviderResponseFailed:
      summary: Verify DCR Provider Failed Response
      value:
        status: failed
        errors:
          - Unable to create the DCR application
    CreateAppAuthStrategyKeyAuthRequest:
      value:
        name: auth strategy 1
        display_name: API Key Auth
        strategy_type: key_auth
        configs:
          key-auth:
            key_names:
              - apikey
              - api-key
              - x-api-key
        dcr_provider_id: null
    CreateAppAuthStrategyOpenIDConnectRequest:
      value:
        name: auth strategy 2
        display_name: Enterprise Auth
        strategy_type: openid_connect
        configs:
          openid-connect:
            issuer: https://oidc.example.com
            credential_claim:
              - client_id
            scopes:
              - openid
              - email
            auth_methods:
              - client_credentials
              - bearer
        dcr_provider_id: 73f8380e-7798-4566-99e3-2edf2b57d281
    UpdateAppAuthStrategyKeyAuthRequest:
      value:
        display_name: API Key
    UpdateAppAuthStrategyOpenIDConnectRequest:
      value:
        display_name: Client Credentials
    AppAuthStrategyResponseExample1:
      value:
        id: 22f8380e-7798-4566-99e3-2edf2b57d289
        name: auth strategy 1
        display_name: Client Credentials
        strategy_type: openid_connect
        active: false
        configs:
          openid-connect:
            issuer: https://my-issuer.example.com/default
            auth_methods:
              - client_credentials
            credential_claim:
              - client_id
            scopes:
              - openid
              - email
        dcr_provider:
          id: 33f8380e-7798-4566-99e3-2edf2b57d289
          name: DCR Provider 1
          display_name: Credentials
          provider_type: http
        created_at: '2023-01-01T00:00:00.000Z'
        updated_at: '2023-01-01T00:00:00.000Z'
    ListAppAuthStrategyResponseExample1:
      value:
        data:
          - id: 22f8380e-7798-4566-99e3-2edf2b57d289
            name: auth strategy 1
            display_name: Client Credentials
            strategy_type: openid_connect
            active: false
            configs:
              openid-connect:
                issuer: https://my-issuer.example.com/default
                auth_methods:
                  - client_credentials
                credential_claim:
                  - client_id
                scopes:
                  - openid
                  - email
            dcr_provider:
              id: 33f8380e-7798-4566-99e3-2edf2b57d289
              name: DCR Provider 1
              display_name: Credentials
              provider_type: http
            created_at: '2023-01-01T00:00:00.000Z'
            updated_at: '2023-01-01T00:00:00.000Z'
        meta:
          page:
            number: 1
            size: 1
            total: 10
    PortalProductVersion:
      value:
        id: 22f8380e-7798-4566-99e3-2edf2b57d289
        publish_status: published
        product_version_id: 33f8380e-7798-4566-99e3-2edf2b57d289
        auth_strategy_ids:
          - 44f8380e-7798-4566-99e3-2edf2b57d289
        application_registration_enabled: true
        auto_approve_registration: true
        deprecated: false
        created_at: '2023-01-01T00:00:00.000Z'
        updated_at: '2023-01-01T00:00:00.000Z'
    ListPortalProductVersions:
      value:
        data:
          - id: 22f8380e-7798-4566-99e3-2edf2b57d289
            publish_status: published
            product_version_id: 33f8380e-7798-4566-99e3-2edf2b57d289
            auth_strategy_ids:
              - 44f8380e-7798-4566-99e3-2edf2b57d289
            application_registration_enabled: true
            auto_approve_registration: true
            deprecated: false
            created_at: '2023-01-01T00:00:00.000Z'
            updated_at: '2023-01-01T00:00:00.000Z'
        meta:
          page:
            number: 1
            size: 1
            total: 10
    PortalProductVersionCreateRequest:
      value:
        product_version_id: 33f8380e-7798-4566-99e3-2edf2b57d289
        auth_strategy_ids:
          - 44f8380e-7798-4566-99e3-2edf2b57d289
        publish_status: published
        application_registration_enabled: true
        auto_approve_registration: true
        deprecated: false
    PortalProductVersionUpdateRequest:
      value:
        auto_approve_registration: false
    UnauthorizedExample:
      value:
        status: 401
        title: Unauthorized
        instance: kong:trace:8347343766220159418
        detail: Unauthorized
    ForbiddenExample:
      value:
        status: 403
        title: Forbidden
        instance: kong:trace:2723154947768991354
        detail: You do not have permission to perform this action
    NotFoundExample:
      value:
        status: 404
        title: Not Found
        instance: kong:trace:6816496025408232265
        detail: Not Found
