openapi: 3.0.2
info:
  title: Konnect Organization Settings API - Beta
  version: 0.0.0
  description: The management API for Kong Konnect Organization Settings resources.
  contact:
    name: Kong
    url: 'https://konghq.com'
servers:
  - url: 'https://us.api.konghq.com/v2'
    description: US URL
  - url: 'https://eu.api.konghq.com/v2'
    description: EU URL
paths:
  /audit-log-replay-job:
    put:
      summary: Create or replace a job to replay audit logs
      description: |-
        _The audit logs feature is currently in beta and is subject to change._

        Creates or replaces a job to replay/re-send audit logs to an organization's webhook.
      operationId: create-audit-log-replay-job
      x-unstable: true
      requestBody:
        $ref: '#/components/requestBodies/CreateAuditLogReplayJob'
      tags: [Audit Logs]
      responses:
        '202':
          $ref: '#/components/responses/AuditLogReplayJob'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
    get:
      summary: Get Audit Log Replay Job
      description: |-
        _The audit logs feature is currently in beta and is subject to change._

        Returns the audit log replay job's configuration and status.
      operationId: get-audit-log-replay-job
      x-unstable: true
      tags: [Audit Logs]
      responses:
        '200':
          $ref: '#/components/responses/AuditLogReplayJob'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
  /audit-log-webhook:
    patch:
      summary: Update Audit Log Webhook
      description: |-
        _The audit logs feature is currently in beta and is subject to change._

        Updates the configuration for a webhook to receive audit logs.
      operationId: update-audit-log-webhook
      x-unstable: true
      requestBody:
        $ref: '#/components/requestBodies/UpdateAuditLogWebhook'
      tags: [Audit Logs]
      responses:
        '200':
          $ref: '#/components/responses/AuditLogWebhook'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
    put:
      deprecated: true
      summary: Replace Audit Log Webhook
      description: |-
        _The audit logs feature is currently in beta and is subject to change._

        Sets configuration for a webhook to receive audit logs.
      operationId: replace-audit-log-webhook
      x-unstable: true
      requestBody:
        $ref: '#/components/requestBodies/CreateAuditLogWebhook'
      tags: [Audit Logs]
      responses:
        '200':
          $ref: '#/components/responses/AuditLogWebhook'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
    get:
      summary: Get Audit Log Webhook
      description: |-
        _The audit logs feature is currently in beta and is subject to change._

        Returns configuration for the audit log webhook.
      operationId: get-audit-log-webhook
      x-unstable: true
      tags: [Audit Logs]
      responses:
        '200':
          $ref: '#/components/responses/AuditLogWebhook'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
  /audit-log-webhook/status:
    get:
      summary: Get Audit Log Webhook Status
      description: |-
        _The audit logs feature is currently in beta and is subject to change._

        Returns status of the audit log webhook.
      x-unstable: true
      tags: [Audit Logs]
      responses:
        '200':
          $ref: '#/components/responses/AuditLogWebhookStatus'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
  /audit-log-webhook/jwks.json:
    get:
      operationId: get-audit-log-jwks
      summary: Get Audit Log JSON Web Keys
      description: |-
        _The audit logs feature is currently in beta and is subject to change._
        Returns the public keys used to sign audit log entries in order to verify the 
        validity of audit log entries.
      x-unstable: true
      tags:
        - Audit Logs
      responses:
        '200':
          $ref: '#/components/responses/JWKS'
components:
  responses:
    AuditLogReplayJob:
      description: Get response for an audit log replay job
      content:
        application/json:
          schema:
            type: object
            properties:
              start_at:
                type: string
                format: date-time
                example: '2017-07-21T17:32:28Z'
                description: The start of a date-time range.
              end_at:
                type: string
                format: date-time
                example: '2017-07-21T17:32:28Z'
                description: The end of a date-time range.
              status:
                type: string
                enum: [accepted, completed, failed, running, pending]
                readOnly: true
              created_at:
                type: string
                description: Timestamp of when the audit log replay job was created.
                format: date-time
                readOnly: true
    AuditLogWebhook:
      description: Get response for audit log webhook
      content:
        application/json:
          schema:
            type: object
            properties:
              endpoint:
                type: string
                example: 'https://example.com/audit-logs'
                description: The endpoint that will receive audit log messages.
              enabled:
                type: boolean
                example: true
                description: Indicates whether audit data should be sent to the webhook.
              log_format:
                type: string
                example: cef
                enum: [cef, json]
                description: The output format of each log messages.
                default: cef
          examples:
            Get Audit Log Webhook:
              $ref: '#/components/examples/Get-Audit-Log-Webhook'
    AuditLogWebhookStatus:
      description: Get response for audit log webhook status
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: object
                description: Status of a webhook.
                properties:
                  webhook_status:
                    type: string
                    example: active
                    enum: [active, inactive]
                    description: |- 
                      Current status of a webhook. `active` indicates the webhook is sending or ready to send requests. 
                      `inactive` indicates the webhook has been turned off due to failed attempts.
                  webhook_enabled:
                    type: boolean
                    example: true
                    description: |- 
                      Configured status of a webhook. `enabled` indicates the client will accept requests. 
                      `disabled` indicates the client will not accept requests.
                  last_attempt_at:
                    type: string
                    format: date-time
                    example: '2023-03-21T09:29:14.52Z'
                    description: The last time a request was made to the webhook, regardless of outcome.
                  last_response_code:
                    type: integer
                    example: 401
                    description: The last response code received from the webhook.
                  last_response_message:
                    type: string
                    example: Unauthenticated
                    description: The last message received from the webhook. Useful for debugging.
          examples:
            Get Audit Log Webhook Status:
              $ref: '#/components/examples/Get-Audit-Log-Webhook-Status'
    JWKS:
      description: Get response for the audit log JSON Web Keys
      content:
        application/json:
          schema:
            type: object
            properties:
              keys:
                type: array
                items:
                  $ref: '#/components/schemas/JWK'
          examples:
            JWKS:
              $ref: '#/components/examples/JWKS'
    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            type: object
            description: The error object
            properties:
              status:
                type: integer
                description: The HTTP response code
                example: 400
              title:
                type: string
                example: Bad Request
                description: The Error response
              instance:
                type: string
                description: The Konnect traceback ID.
                example: 'konnect:trace:3674017986744198214'
              invalid_parameters:
                type: array
                description: An array of objects that contains information related to the error response.
                items:
                  type: object
                  properties:
                    field:
                      type: string
                    reason:
                      type: string
          examples:
            Request Format is Invalid:
              $ref: '#/components/examples/400-request-format-is-invalid'
            Authorization Cannot be Blank:
              $ref: '#/components/examples/400-authorization-cannot-be-blank'
            Endpoint Cannot be Blank:
              $ref: '#/components/examples/400-endpoint-cannot-be-blank'
            Endpoint Must be a valid URL:
              $ref: '#/components/examples/400-endpoint-must-be-valid-url'
    Conflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            type: object
            description: The error object
            properties:
              status:
                type: integer
                description: The HTTP response code
                example: 409
              title:
                type: string
                example: Resource Conflict
                description: The Error response
              instance:
                type: string
                description: The Konnect traceback ID.
                example: 'konnect:trace:3674017986744198214'
              detail:
                type: string
                description: Detailed explanation of the error response.
                example: A replay job is currently running
          examples:
            Job Running:
              $ref: '#/components/examples/409-job-running'
    Unauthenticated:
      description: Unauthenticated
      content:
        application/problem+json:
          schema:
            type: object
            x-examples:
              Example 1:
                status: 401
                title: Unauthenticated
                instance: 'konnect:trace:952172606039454040'
                detail: A valid token is required
            description: The error response object.
            properties:
              status:
                type: integer
                example: 401
                description: The HTTP status code.
              title:
                type: string
                description: The Error Response.
                example: Unauthenticated
              instance:
                type: string
                description: The Konnect traceback code.
                example: 'konnect:trace:952172606039454040'
              detail:
                type: string
                description: Details about the error response.
                example: A valid token is required
          examples:
            Unauthorized:
              $ref: '#/components/examples/401-unauthenticated'
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            type: object
            x-examples:
              Example:
                status: 403
                title: Unauthorized
                instance: 'konnect:trace:952172606039454040'
                detail: You do not have permission to perform this action
            description: The error response object.
            properties:
              status:
                type: integer
                example: 403
                description: The HTTP status code.
              title:
                type: string
                description: The Error Response.
                example: Unauthorized
              instance:
                type: string
                description: The Konnect traceback code.
                example: 'konnect:trace:952172606039454040'
              detail:
                type: string
                description: Details about the error response.
                example: You do not have permission to perform this action
          examples:
            Unauthorized:
              $ref: '#/components/examples/403-permission-denied'
  requestBodies:
    CreateAuditLogReplayJob:
      description: The request schema to create/replace an audit log replay job.
      content:
        application/json:
          schema:
            type: object
            required:
              - start
              - end
            properties:
              start_at:
                type: string
                format: date-time
                description: |- 
                  The start of a date-time range in RFC3339 format e.g. 2017-07-21T17:32:28Z.
                  Within the last 7 days.
              end_at:
                type: string
                format: date-time
                description: |-
                  The end of a date-time range in RFC3339 format e.g. 2017-07-21T17:32:28Z.
                  Within the last 7 days.
    CreateAuditLogWebhook:
      description: The request schema to create or replace an audit log webhook.
      content:
        application/json:
          schema:
            type: object
            required: 
              - endpoint
              - authorization
            properties:
              endpoint:
                type: string
                example: 'https://example.com/audit-logs'
                description: The endpoint that will receive audit log messages.
              authorization:
                type: string
                example: 'Bearer sometoken'
                description: The value to include in the `Authorization` header when sending audit logs
              enabled:
                type: boolean
                example: true
                description: Indicates if the data should be sent to the webhook.
              log_format:
                type: string
                example: cef
                enum: [cef, json]
                description: The output format of each log messages.
                default: cef
          examples:
            Example Request Body:
              $ref: '#/components/examples/Create-Audit-Log-Webhook'
    UpdateAuditLogWebhook:
      description: The request schema to modify an audit log webhook.
      content:
        application/json:
          schema:
            type: object
            properties:
              endpoint:
                type: string
                example: 'https://example.com/audit-logs'
                description: The endpoint that will receive audit log messages.
              authorization:
                type: string
                example: 'Bearer sometoken'
                description: The value to include in the `Authorization` header when sending audit logs
              enabled:
                type: boolean
                example: true
                description: Indicates if the data should be sent to the webhook.
              log_format:
                type: string
                example: cef
                enum: [cef, json]
                description: The output format of each log messages.
                default: cef
          examples:
            Disable Webhook:
              $ref: '#/components/examples/Update-Audit-Log-Webhook'
            Enable Webhook:
              $ref: '#/components/examples/Create-Audit-Log-Webhook'
  securitySchemes:
    personalAccessToken:
      $ref: '../../../../../common/definitions/security.yaml#/components/securitySchemes/personalAccessToken'
    systemAccountAccessToken:
      $ref: '../../../../../common/definitions/security.yaml#/components/securitySchemes/systemAccountAccessToken'
  examples:
    400-request-format-is-invalid:
      value:
        status: 400
        title: Bad Request
        instance: 'konnect:trace:3674017986744198214'
        invalid_parameters:
          - field: body
            reason: request format is invalid
    400-authorization-cannot-be-blank:
      value:
        status: 400
        title: Bad Request
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: authorization
            reason: cannot be blank
    400-endpoint-cannot-be-blank:
      value:
        status: 400
        title: Bad Request
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: endpoint
            reason: cannot be blank
    400-endpoint-must-be-valid-url:
      value:
        status: 400
        title: Bad Request
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: endpoint
            reason: must be a valid URL
    403-permission-denied:
      value:
        status: 403
        title: Permission denied
        instance: 'konnect:trace:2822394689570210664'
        detail: Only enterprise organizations can perform this action
    409-job-running:
      value:
        status: 409
        title: Resource Conflict
        instance: 'konnect:trace:6644808935508571943'
        detail: A replay job is currently running
    401-unauthenticated:
      value:
        status: 401
        title: Unauthenticated
        instance: 'konnect:trace:952172606039454040'
        detail: A valid token is required
    Create-Audit-Log-Webhook:
      value:
        endpoint: https://example.com/audit-log
        authorization: 'Bearer sometoken'
        enabled: true
        log_format: json
    Update-Audit-Log-Webhook:
      value:
        enabled: false
    Get-Audit-Log-Webhook:
      value:
        endpoint: https://example.com/audit-log
        authorization: 'Bearer sometoken'
        enabled: true
        log_format: cef
    Get-Audit-Log-Webhook-Status:
      value:
        webhook_enabled: true
        webhook_status: inactive
        last_attempt_at: '2023-03-21T09:29:14.52Z'
        last_response_code: 401
        last_response_message: Unauthorized
    JWKS:
      value:
        keys:
          - kty: OKP
            alg: EdDSA
            kid: 3f60bc4376c937154f3c004ebd180433ac0d03e6
            crv: Ed25519
            x: XWxGtApfcqmKI7p0OKnF5JSEWMVoLsytFXLEP7xZ_l8
    JWK:
      value:
        kty: OKP
        alg: EdDSA
        kid: 3f60bc4376c937154f3c004ebd180433ac0d03e6
        crv: Ed25519
        x: XWxGtApfcqmKI7p0OKnF5JSEWMVoLsytFXLEP7xZ_l8
  schemas:
    JWK:
      title: JWK
      type: object
      description: An individual JSON Web Key.
      properties:
        kty:
          type: string
          description: The algorithm family of the key.
        alg:
          type: string
          description: The algorithm intended for use with the key.
        kid:
          type: string
          description: The unique ID of the key.
        crv:
          type: string
          description: The cryptographic curve used with the key.
        x:
          type: string
          description: The x coordinate for the Elliptic Curve point.
      x-examples:
        JWK:
          $ref: '#/components/examples/JWK'
security:
  - personalAccessToken: []
  - systemAccountAccessToken: []
tags:
  - name: Audit Logs
