openapi: 3.0.3
info:
  title: Portal Management
  version: 2.2.0
  description: The management API for Portals
  contact:
    name: Kong
    url: 'https://konghq.com'
servers:
  - url: 'https://us.api.konghq.com/v2'
    description: US Region Base URL
  - url: 'https://eu.api.konghq.com/v2'
    description: EU Region Base URL
  - url: 'https://au.api.konghq.com/v2'
    description: AU Region Base URL
paths:
  '/portals/{portalId}/audit-log-replay-job':
    parameters:
      - $ref: '#/components/parameters/parameters-PortalId'
    put:
      operationId: update-portal-audit-log-replay-job
      summary: Update Portal Audit Log Replay Job
      description: Updates a job to re-send audit logs to an portal's webhook.
      requestBody:
        $ref: '#/components/requestBodies/ReplacePortalAuditLogReplayJob'
      responses:
        '202':
          $ref: '#/components/responses/PortalAuditLogReplayJob'
        '400':
          $ref: '#/components/responses/PortalReplayJobBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/PortalReplayJobConflict'
      tags:
        - Portal Audit Logs
    get:
      operationId: get-portal-audit-log-replay-job
      summary: Get Portal Audit Log Replay Job
      description: Returns the audit log replay job's configuration and status.
      responses:
        '200':
          $ref: '#/components/responses/PortalAuditLogReplayJob'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Portal Audit Logs
  '/portals/{portalId}/audit-log-webhook':
    parameters:
      - $ref: '#/components/parameters/parameters-PortalId'
    patch:
      operationId: update-portal-audit-log-webhook
      summary: Update Portal Audit Log Webhook
      description: Updates the configuration for a webhook to receive audit logs.
      requestBody:
        $ref: '#/components/requestBodies/UpdatePortalAuditLogWebhook'
      responses:
        '200':
          $ref: '#/components/responses/PortalAuditLogWebhook'
        '400':
          $ref: '#/components/responses/PortalWebhookBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Portal Audit Logs
    get:
      operationId: get-portal-audit-log-webhook
      summary: Get Portal Audit Log Webhook
      description: Returns configuration for the audit log webhook.
      responses:
        '200':
          $ref: '#/components/responses/PortalAuditLogWebhook'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Portal Audit Logs
  '/portals/{portalId}/audit-log-webhook/status':
    parameters:
      - $ref: '#/components/parameters/parameters-PortalId'
    get:
      operationId: get-portal-audit-log-webhook-status
      summary: Get Portal Audit Log Webhook Status
      description: Returns status of the audit log webhook.
      responses:
        '200':
          $ref: '#/components/responses/PortalAuditLogWebhookStatus'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Portal Audit Logs
components:
  parameters:
    parameters-PortalId:
      schema:
        type: string
        format: uuid
      name: portalId
      in: path
      required: true
      description: ID of the portal.
  schemas:
    BaseError:
      description: standard error
      type: object
      properties:
        status:
          description: |
            The HTTP status code of the error. Useful when passing the response
            body to child properties in a frontend UI. Must be returned as an integer.
          type: integer
          readOnly: true
        title:
          description: |
            A short, human-readable summary of the problem. It should not
            change between occurences of a problem, except for localization.
            Should be provided as "Sentence case" for direct use in the UI.
          type: string
          readOnly: true
        type:
          description: The error type.
          type: string
          readOnly: true
        instance:
          description: |
            Used to return the correlation ID back to the user, in the format
            kong:trace:<correlation_id>. This helps us find the relevant logs
            when a customer reports an issue.
          type: string
          readOnly: true
        detail:
          description: |
            A human readable explanation specific to this occurence of the problem.
            This field may contain request/entity data to help the user understand
            what went wrong. Enclose variable values in square brackets. Should be
            provided as "Sentence case" for direct use in the UI.
          type: string
          readOnly: true
      required:
        - status
        - title
        - instance
        - detail
      title: Error
    InvalidRules:
      description: invalid parameters rules
      type: string
      enum:
        - required
        - max_length
        - is_array
        - is_base64
        - is_boolean
        - is_date_time
        - is_integer
        - is_null
        - is_number
        - is_object
        - is_string
        - is_uuid
        - is_fqdn
        - is_arn
        - unknown_property
        - is_label
        - matches_regex
        - invalid
        - is_supported_network_availability_zone_list
        - is_supported_network_cidr_block
        - is_supported_provider_region
      nullable: true
      readOnly: true
    InvalidParameterStandard:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          $ref: '#/components/schemas/InvalidRules'
        source:
          type: string
          example: body
        reason:
          type: string
          example: is a required field
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
    InvalidParameterMinimumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - min_length
            - min_digits
            - min_lowercase
            - min_uppercase
            - min_symbols
          nullable: false
          readOnly: true
        minimum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: is a required field
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - minimum
    InvalidParameterChoiceItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - enum
          nullable: false
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        choices:
          type: array
          items: {}
          minimum: 1
          nullable: false
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - choices
    InvalidParameterDependentItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - dependent_fields
          nullable: true
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        dependents:
          type: array
          items: {}
          nullable: true
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
        - field
        - rule
        - reason
        - dependents
    InvalidParameters:
      description: invalid parameters
      type: array
      items:
        oneOf:
          - $ref: '#/components/schemas/InvalidParameterStandard'
          - $ref: '#/components/schemas/InvalidParameterMinimumLength'
          - $ref: '#/components/schemas/InvalidParameterChoiceItem'
          - $ref: '#/components/schemas/InvalidParameterDependentItem'
      minItems: 1
      nullable: false
      uniqueItems: true
    BadRequestError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          required:
            - invalid_parameters
          properties:
            invalid_parameters:
              $ref: '#/components/schemas/InvalidParameters'
    UnauthorizedError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 401
            title:
              example: Unauthorized
            type:
              example: 'https://httpstatuses.com/401'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Invalid credentials
    ForbiddenError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 403
            title:
              example: Forbidden
            type:
              example: 'https://httpstatuses.com/403'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Forbidden
    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 404
            title:
              example: Not Found
            type:
              example: 'https://httpstatuses.com/404'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Not found
    ConflictError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 409
            title:
              example: Conflict
            type:
              example: 'https://httpstatuses.com/409'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Conflict
  examples:
    400-request-format-is-invalid:
      value:
        status: 400
        title: Bad Request
        detail: Could not parse request body
        instance: 'konnect:trace:3674017986744198214'
        invalid_parameters:
          - field: body
            reason: request format is invalid
    400-authorization-cannot-be-blank:
      value:
        status: 400
        title: Bad Request
        detail: Required field missing
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: authorization
            reason: cannot be blank
    400-endpoint-cannot-be-blank:
      value:
        status: 400
        title: Bad Request
        detail: Required field missing
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: endpoint
            reason: cannot be blank
    400-endpoint-must-be-valid-url:
      value:
        status: 400
        title: Bad Request
        detail: Invalid endpoint
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: endpoint
            reason: must be a valid URL
    409-job-running:
      value:
        status: 409
        title: Resource Conflict
        instance: 'konnect:trace:6644808935508571943'
        detail: A replay job is currently running
    Update-Portal-Audit-Log-Webhook:
      value:
        audit_log_destination_id: 9cb77dc2-ff99-4d47-84ab-7c5c1b3ef939
    Disable-Portal-Audit-Log-Webhook:
      value:
        enabled: false
    Enable-Portal-Audit-Log-Webhook:
      value:
        enabled: true
    Get-Portal-Audit-Log-Webhook:
      value:
        enabled: true
        audit_log_destination_id: 9cb77dc2-ff99-4d47-84ab-7c5c1b3ef939
    Get-Portal-Audit-Log-Webhook-Status:
      value:
        webhook_enabled: true
        webhook_status: inactive
        last_attempt_at: '2023-03-21T09:29:14.52Z'
        last_response_code: 401
        last_response_message: Unauthorized
    UnauthorizedExample:
      value:
        status: 401
        title: Unauthorized
        instance: 'kong:trace:8347343766220159418'
        detail: Unauthorized
    ForbiddenExample:
      value:
        status: 403
        title: Forbidden
        instance: 'kong:trace:2723154947768991354'
        detail: You do not have permission to perform this action
    NotFoundExample:
      value:
        status: 404
        title: Not Found
        instance: 'kong:trace:6816496025408232265'
        detail: Not Found
  requestBodies:
    ReplacePortalAuditLogReplayJob:
      description: The request schema to replace a portal audit log replay job.
      content:
        application/json:
          schema:
            type: object
            properties:
              start_at:
                description: |-
                  The start of a date-time range in RFC3339 format e.g. 2017-07-21T17:32:28Z.
                  Must be within the last 7 days.
                type: string
                format: date-time
              end_at:
                description: |-
                  The end of a date-time range in RFC3339 format e.g. 2017-07-21T17:32:28Z.
                  Must be within the last 7 days.
                type: string
                format: date-time
            required:
              - start_at
              - end_at
    UpdatePortalAuditLogWebhook:
      description: The request schema to modify an portal audit log webhook.
      content:
        application/json:
          schema:
            type: object
            properties:
              enabled:
                description: Indicates if the data should be sent to the configured destination.
                type: boolean
                example: true
                default: false
              audit_log_destination_id:
                description: ID of the audit log destination.
                type: string
                format: uuid
          examples:
            Disable Webhook:
              $ref: '#/components/examples/Disable-Portal-Audit-Log-Webhook'
            Enable Webhook:
              $ref: '#/components/examples/Enable-Portal-Audit-Log-Webhook'
            Update Webhook:
              $ref: '#/components/examples/Update-Portal-Audit-Log-Webhook'
  responses:
    PortalAuditLogReplayJob:
      description: Response from fetching or updating an portal audit log replay job
      content:
        application/json:
          schema:
            type: object
            properties:
              start_at:
                description: 'The start of a date-time range. Initial value is 0001-01-01T00:00:0Z.'
                type: string
                format: date-time
                example: '2017-07-21T17:32:28Z'
              end_at:
                description: 'The end of a date-time range. Initial value is 0001-01-01T00:00:0Z.'
                type: string
                format: date-time
                example: '2017-07-21T17:32:28Z'
              status:
                type: string
                enum:
                  - unconfigured
                  - accepted
                  - pending
                  - running
                  - completed
                  - failed
                readOnly: true
              updated_at:
                description: 'Timestamp when this job was last updated. Initial value is 0001-01-01T00:00:0Z.'
                type: string
                format: date-time
                readOnly: true
    PortalAuditLogWebhook:
      description: Portal audit log webhook response
      content:
        application/json:
          schema:
            type: object
            properties:
              enabled:
                description: Indicates if the data should be sent to the configured audit log destination.
                type: boolean
                example: true
                default: false
              audit_log_destination_id:
                description: ID of the audit log destination.
                type: string
                format: uuid
          examples:
            Get Portal Audit Log Webhook:
              $ref: '#/components/examples/Get-Portal-Audit-Log-Webhook'
    PortalAuditLogWebhookStatus:
      description: Get response for portal audit log webhook status
      content:
        application/json:
          schema:
            type: object
            properties:
              webhook_status:
                description: |-
                  Current status of a webhook. `active` indicates the webhook is sending or ready to send requests. 
                  `inactive` indicates the webhook has been turned off due to failed attempts.
                type: string
                example: active
                enum:
                  - active
                  - inactive
              webhook_enabled:
                description: |-
                  Configured status of a webhook. `enabled` indicates the client will accept requests. 
                  `disabled` indicates the client will not accept requests.
                type: boolean
                example: true
              last_attempt_at:
                description: 'The last time a request was made to the webhook, regardless of outcome.'
                type: string
                format: date-time
                example: '2023-03-21T09:29:14.52Z'
              last_response_code:
                description: The last response code received from the webhook.
                type: integer
                example: 401
              last_response_message:
                description: The last message received from the webhook. Useful for debugging.
                type: string
                example: Unauthenticated
          examples:
            Get Audit Log Webhook Status:
              $ref: '#/components/examples/Get-Portal-Audit-Log-Webhook-Status'
    PortalWebhookBadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BadRequestError'
          examples:
            Request Format is Invalid:
              $ref: '#/components/examples/400-request-format-is-invalid'
            Authorization Cannot be Blank:
              $ref: '#/components/examples/400-authorization-cannot-be-blank'
            Endpoint Cannot be Blank:
              $ref: '#/components/examples/400-endpoint-cannot-be-blank'
            Endpoint Must be a valid URL:
              $ref: '#/components/examples/400-endpoint-must-be-valid-url'
    PortalReplayJobBadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BadRequestError'
    PortalReplayJobConflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ConflictError'
          examples:
            Job Running:
              $ref: '#/components/examples/409-job-running'
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/UnauthorizedExample'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/ForbiddenExample'
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
          examples:
            NotFoundExample:
              $ref: '#/components/examples/NotFoundExample'
  securitySchemes:
    personalAccessToken:
      type: http
      scheme: bearer
      bearerFormat: Token
      description: |
        The personal access token is meant to be used as an alternative to basic-auth when accessing Konnect via APIs.
        You can generate a Personal Access Token (PAT) from the [personal access token page](https://cloud.konghq.com/global/tokens/) in the Konnect dashboard.
        The PAT token must be passed in the header of a request, for example:
        `curl -X GET 'https://global.api.konghq.com/v2/users/' --header 'Authorization: Bearer kpat_xgfT...'`
    systemAccountAccessToken:
      type: http
      scheme: bearer
      bearerFormat: Token
      description: |
        The system account access token is meant for automations and integrations that are not directly associated with a human identity.
        You can generate a system account Access Token by creating a system account and then obtaining a system account access token for that account.
        The access token must be passed in the header of a request, for example:
        `curl -X GET 'https://global.api.konghq.com/v2/users/' --header 'Authorization: Bearer spat_i2Ej...'`
tags: []
security:
  - personalAccessToken: []
  - systemAccountAccessToken: []
